language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: FO9dOogOdTZoalVLpTKa/i0Z8JIH5sEJOjSPvC90QUIzgn5+PxXqoz4Uzrci2wvDTxnWJ+zFrAbDKUzu876LxjJHGgkfZVWn5PMkGKpU0/bfpY5m+cPL5BmOGA7fjpophlsnoLonJGYs+gt78sb9mshLJfE5K22OVTmxgQ0ygwSuS5f4IDQpsZPSeNmyX0LhTLfep2UIPy17th9b82e5Ky1SORP+QRN0lbvzWfRT2ZFO8lvnszqNFDGZHtYu8+4m7l12FSwfSnxoe70P2yDlDB3Cehi7mZBKmETQ1KlUtsv06S5mKouxxu1RzM7eTExBoZBdt3x2w6mMfZuNx1wMK6/yppz0hxMliGBE+4IarPOP/5+N9EXY7FcilvjL1TJS7tJGQjoxhV5yQLUYcAzfRkqV3Kp3T5PQe27jlTzCWLTfG7cZaagTlXKGXzF6Mhnjq5Wm11LupHp4Uqu0rlyNUQuRvHhvReKIKaUk/fdH0hVETkloazGgGpimeDfAXy/zI4CQlulE4wnyv2rppj/SHn6JT61wfl0QxEgnNOCUI/5nAuJnz/HtbCqN1kB5S7TF0qDQRgaMXm7/ZAxElAQDygqsZDKI06KQpk/h1UEOHiPeAK+GwhxxZvIVgMuNMq7JV4/73JEM9TGivVx8o5G/LHgFQEo9zJ43+iQ0bzDO0xs=
  app: istic-api
